### ISSUE TITLE
[Bug] Extension not working, content all white

### ISSUE THREAD

**Issue by mariogarridopt** [mariogarridopt/Rocket-Launch-Schedule#34]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/mariogarridopt/Rocket-Launch-Schedule/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Rocket Launch Shedule installed as the only extension.

### Bug Description

When you open the extension there is no content inside the window, all white color

### Steps To Reproduce

Open the extension

### Expected Behavior

List of launches

### Actual Behavior

No list

### Web Browser name and version

Firefox

### Rocket Launch Schedule version

latest

**Comment by mariogarridopt** [comment]
The problem is the following:

The extension calls `https://ll.thespacedevs.com/2.0.0/launch/upcoming/?limit=10&mode=detailed` for the launch list;
**The list comes with some future launches and some past launches**, the extension will then filter the past launches out:
https://github.com/mariogarridopt/Rocket-Launch-Schedule/blob/8fe1015f3585d9a5c008c6e0884e4c55db974af8/js/launchHTML.js#L15-L19

If the list of 10 has more past launches than future ones, the extension will be compromised, because it will not have enough launches to populate the window.

For now, a new patch was released that will increase the API fetch to get 20 instead of 10 results and that will give us a bigger buffer to handle past launches.

> This is not the final fix because this is not fail-proof, in a week with a lot of launches 20 might not be enough of a buffer.
> I'm searching if I can query the API with a `?start-date=...` kind of param, so we can only get useful data.

**Comment by Nosudrum** [comment]
> The list comes with some future launches and some past launches, the extension will then filter the past launches out

You can do that directly with the `hide_recent_previous=true` filter on the `/launch/upcoming` endpoint, as explained [here](https://github.com/TheSpaceDevs/Tutorials/blob/main/faqs/faq_LL2.md#why-do-past-items-appear-in-the-upcoming-endpoints).

> I'm searching if I can query the API with a ?start-date=... kind of param, so we can only get useful data.

If you still need this after seeing the above, it can be done using the `net__gte=2023-01-25T01:23:45Z` filter on the `/launch` endpoint. The datetime string is formatted according to [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).

**Comment by Nosudrum** [comment]
Seems to be working again for some reason
